# Generated by Django 5.1.1 on 2024-09-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('new', 'Новое'), ('used', 'Б/У')], default='new', max_length=10, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контакт авторизованного сервиса'),
        ),
    ]
