# Generated by Django 5.1.1 on 2024-09-13 07:14

import equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_condition_equipment_service_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=equipment.models.equipment_document_path, verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего обслуживания'),
        ),
    ]
